/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Klinger
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuConsulta = new javax.swing.JMenu();
        menuMarcarConsulta = new javax.swing.JMenu();
        menuCancelarConsulta = new javax.swing.JMenu();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroPaciente = new javax.swing.JMenu();
        menuCadastroMedico = new javax.swing.JMenu();
        menuCadastroPlanoSaude = new javax.swing.JMenu();
        menuCadastroProcedimento = new javax.swing.JMenu();
        menuPesquisar = new javax.swing.JMenu();
        menuBuscaConsulta = new javax.swing.JMenu();
        menuBuscaPaciente = new javax.swing.JMenu();
        menuBuscaMedico = new javax.swing.JMenu();
        menuBuscaProcedimento = new javax.swing.JMenu();
        menuBuscaPlanoSaude = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medice Center");
        setName("telaPrincipal"); // NOI18N

        menuConsulta.setText("Consulta");

        menuMarcarConsulta.setText("Marcar");
        menuConsulta.add(menuMarcarConsulta);

        menuCancelarConsulta.setText("Cancelar");
        menuConsulta.add(menuCancelarConsulta);

        jMenuBar1.add(menuConsulta);

        menuCadastro.setText("Cadastro");

        menuCadastroPaciente.setText("Paciente");
        menuCadastro.add(menuCadastroPaciente);

        menuCadastroMedico.setText("Médico");
        menuCadastro.add(menuCadastroMedico);

        menuCadastroPlanoSaude.setText("Plano de Saúde");
        menuCadastro.add(menuCadastroPlanoSaude);

        menuCadastroProcedimento.setText("Procedimento");
        menuCadastro.add(menuCadastroProcedimento);

        jMenuBar1.add(menuCadastro);

        menuPesquisar.setText("Busca Rápida");

        menuBuscaConsulta.setText("Consulta");
        menuPesquisar.add(menuBuscaConsulta);

        menuBuscaPaciente.setText("Paciente");
        menuPesquisar.add(menuBuscaPaciente);

        menuBuscaMedico.setText("Médico");
        menuPesquisar.add(menuBuscaMedico);

        menuBuscaProcedimento.setText("Procedimento");
        menuPesquisar.add(menuBuscaProcedimento);

        menuBuscaPlanoSaude.setText("Plano de Saúde");
        menuPesquisar.add(menuBuscaPlanoSaude);

        jMenuBar1.add(menuPesquisar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuBuscaConsulta;
    private javax.swing.JMenu menuBuscaMedico;
    private javax.swing.JMenu menuBuscaPaciente;
    private javax.swing.JMenu menuBuscaPlanoSaude;
    private javax.swing.JMenu menuBuscaProcedimento;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuCadastroMedico;
    private javax.swing.JMenu menuCadastroPaciente;
    private javax.swing.JMenu menuCadastroPlanoSaude;
    private javax.swing.JMenu menuCadastroProcedimento;
    private javax.swing.JMenu menuCancelarConsulta;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenu menuMarcarConsulta;
    private javax.swing.JMenu menuPesquisar;
    // End of variables declaration//GEN-END:variables
}
